name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@master

      #- name: PHPUnit Tests
        #uses: php-actions/phpunit@dynamic-docker
        #with:
          #configuration: phpunit.xml
          #args: --coverage-text
